GIS test1/Models/Dir.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GIS_test1.Models
{
    public class Dir
    {
        public string Name { get; set; }
        public string Path { get; set; }
    }
}

GIS test1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GIS_test1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

GIS test1/Controllers/PhotosController.cs
using GIS_test1.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GIS_test1.Controllers
{
    public class PhotosController : Controller
    {
        const string dataPath = "~/App_Data/";

        public ActionResult Index() {
            return View();
        }

        public ActionResult GetDir()
        {
            ViewBag.Dirs = Finder.FindDirs(Server.MapPath(dataPath));
            return View();
            //return Json(Finder.Find(Server.MapPath(dataPath)), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetFiles(string id)
        {
            ViewBag.Files = Finder.FindFiles(Server.MapPath(dataPath + id));
            ViewBag.Dir = id;
            return View();
            //return Json(Finder.Find(Server.MapPath(dataPath + id)), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(string id,string file)
        {
            ViewBag.Mess = Deleter.Delete(Server.MapPath(dataPath + id), file);
            return View();
            //return Json(Deleter.Delete(Server.MapPath(dataPath + id), file), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, string name, string dir)
        {
            string mess = "";

            if (!Directory.Exists(Server.MapPath(dataPath + dir))){
                Directory.CreateDirectory(Server.MapPath(dataPath + dir));
            }

            var path = Path.Combine(Server.MapPath(dataPath + dir), name + Path.GetExtension(file.FileName));

            if (!System.IO.File.Exists(path)){
                if (file != null && file.ContentLength > 0){
                    file.SaveAs(path);
                }
                mess = "Plik dodano do katalogu";
            }else{
                mess = "Plik o takiej nazwie już istnieje";
            }

            ViewBag.Mess = mess;
            return View();
        }
	}
}

GIS test1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "HOME";
}

<div class="row">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
        <div class="well">
            <h2>
                Gabriel Rogala - GIS test
            </h2>
            <button onclick="location.href = '@Url.Action("GetPhotos", "Photos")'" type="button" class="btn btn-default">PHOTOS</button>
            <button onclick="location.href = '@Url.Action("Upload", "Photos")'" type="button" class="btn btn-default">UPLOAD</button>

        </div>
    </div>
</div>

GIS test1/Views/Photos/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
        <div class="well">
            <h3>@ViewBag.Mess</h3>
        </div>
    </div>
</div>

GIS test1/Views/Photos/GetDir.cshtml
@{
    ViewBag.Title = "GetPhotos";
}


    <div class="row">
        <div class="col-md-offset-3 col-md-6 col-xs-12">
            <div class="well">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <td>
                                ID
                            </td>
                            <td>
                                Action
                            </td>
                        </tr>
                    </thead>
                    @{
                        foreach (var dir in ViewBag.Dirs)
                        {
                            <tr>
                                <td>
                                    @dir.Name
                                </td>
                                <td>
                                    <button onclick="location.href = '@Url.Action("GetPhotos", "Photos", new { id = @dir.Name })'" type="button" class="btn btn-default btn-sm">OPEN</button>
                                </td>
                            </tr>
                        }

                    }
                </table>
            </div>
        </div>
    </div>

GIS test1/Views/Photos/GetFiles.cshtml
@{
    ViewBag.Title = "GetFiles";
}

<div class="row">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
        <div class="well">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <td>
                            ID
                        </td>
                        <td>
                            Action
                        </td>
                    </tr>
                </thead>
                @{
                    foreach (var file in ViewBag.Files)
                    {
                        <tr>
                            <td>
                                @file.Name
                            </td>
                            <td>
                                <button onclick="location.href = '@Url.Action("Delete", "Photos", new { id = @ViewBag.Dir, file = @file.Name })/'" type="button" class="btn btn-default btn-sm">Delete</button>
                            </td>
                        </tr>
                    }

                }
            </table>
        </div>
    </div>
</div>

GIS test1/Views/Photos/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

GIS test1/Views/Photos/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<div class="row">
    <div class="col-sm-offset-2 col-sm-8">
        <div class="well">
            <div class="row">
                @ViewBag.mess
            </div>
            @using (Html.BeginForm("Upload", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <div class="row">
                        <label class="col-sm-3 control-label">Nazwa pliku:</label>
                        <div class="col-sm-9">
                            <input class="form-control" type="text" name="name" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label">Nazwa katalogu:</label>
                        <div class="col-sm-9">
                            <input class="form-control" type="text" name="dir" />
                        </div>
                    </div>
                    <div class="row">
                        <label class="col-sm-3 control-label">Plik:</label>
                        <div class="col-sm-9">
                            <input class="form-control" type="file" name="file" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-10">
                            <input class="btn btn-default" type="submit" value="Zapisz" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

GIS test1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GIS test", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>